fishjam-cloud/web-client-sdk

- .github/dependabot.yml
It looks my previous config was invalid. And GH does not provide easy way for config validation, apart from just merging it...
https://github.com/dependabot/dependabot-core/issues/4605
> [quick-fix] Fix dependabot config

- packages/react-client/src/useSetupMedia.tsx
The screen share track is being removed on any stopped event for any `TrackType` (`audio`, `video`, or `audiovideo`).
When the user stops screen sharing from the browser popup, the track is not removed.
> FCE-263 Stop screen share on browser event

- examples/react-client/videoroom/.eslintignore
- examples/react-client/videoroom/.eslintrc.cjs
- examples/react-client/videoroom/README.md
- examples/react-client/videoroom/package.json
- examples/react-client/videoroom/src/App.tsx
- examples/react-client/videoroom/src/AudioVisualizer.tsx
- examples/react-client/videoroom/src/Button.tsx
- examples/react-client/videoroom/src/RoomConnector.tsx
- examples/react-client/videoroom/src/VideoPlayer.tsx
- examples/react-client/videoroom/src/main.tsx
- examples/react-client/videoroom/vite.config.ts
Allow test app to handle user names in similar way as mobile app
Also add missing lint/format CI checks. And reformat code using our rules
Easier app testing
> [FCE-400] Support names in demo app (and add missing CI checks)

- examples/react-client/use-camera-and-microphone/src/DeviceControls.tsx
- examples/react-client/videoroom/package.json
- examples/react-client/videoroom/public/shaders/blur/fragment.glsl
- examples/react-client/videoroom/public/shaders/blur/vertex.glsl
- examples/react-client/videoroom/src/components/BlurToggle.tsx
- examples/react-client/videoroom/src/components/Button.tsx
- examples/react-client/videoroom/src/components/DevicePicker.tsx
- examples/react-client/videoroom/src/components/VideoPlayer.tsx
- examples/react-client/videoroom/src/utils/blur/BlurProcessor.tsx
- examples/react-client/videoroom/src/utils/blur/BlurProcessorWorker.ts
- packages/react-client/src/Client.ts
- packages/react-client/src/DeviceManager.ts
- packages/react-client/src/create.tsx
- packages/react-client/src/index.ts
- packages/react-client/src/screenShareTrackManager.ts
- packages/react-client/src/state.types.ts
- packages/react-client/src/trackManager.ts
- packages/react-client/src/types.ts
- packages/react-client/src/useSetupMedia.ts
- yarn.lock
Adds track middleware to screenshare and video/audio managers.
Additionally, the track manager has been rewritten from a class to react hook.
Track middleware allows easy manipulation of the tracks managed by the SDK before streaming them out.
I also rewritten the track manager to a hook, because I needed a state to store the middleware.
Adding a property to the TrackManager class wasn't enough, I also needed to synchronize with the react state.
Instead of pursuing the event emitting pattern, I decided to introduce an internal hook.
> Fce 394/track middleware

- examples/react-client/use-camera-and-microphone/src/AdditionalControls.tsx
- examples/react-client/use-camera-and-microphone/src/DeviceControls.tsx
- examples/react-client/use-camera-and-microphone/src/MainControls.tsx
- examples/react-client/videoroom/src/App.tsx
- examples/react-client/videoroom/src/components/BlurToggle.tsx
- examples/react-client/videoroom/src/components/DevicePicker.tsx
- examples/react-client/videoroom/src/components/RoomConnector.tsx
- packages/react-client/src/hooks/devices.ts
- packages/react-client/src/hooks/participants.ts
- packages/react-client/src/hooks/setupMedia.ts
- packages/react-client/src/index.ts
- packages/react-client/src/trackManager.ts
- packages/react-client/src/types.ts
This PR introduces slimmed-down version of the Device API.
We acknowledged the currently exposed Device API is slightly too complicated.
This is a proposal of a simpler one.
```
export type Device = {
streamedTrack: MediaStreamTrack | null;
streamedTrackId: TrackId | null;
stream: MediaStream | null;
devices: MediaDeviceInfo[];
activeDevice: MediaDeviceInfo | null;
} & Omit<TrackManager, "currentTrack">;
export type AudioDevice = Device & { isAudioPlaying: boolean };
export interface TrackManager {
initialize: (deviceId?: string) => Promise<void>;
stop: () => Promise<void>;
startStreaming: (simulcastConfig?: SimulcastConfig, maxBandwidth?: TrackBandwidthLimit) => Promise<string>;
stopStreaming: () => Promise<void>;
pauseStreaming: () => Promise<void>;
resumeStreaming: () => Promise<void>; …
```
> Simplify Device API

- packages/react-client/src/hooks/screenShare.ts
- packages/react-client/src/trackManager.ts
Populate track metadata `displayName` using peer metadata `displayName`.
Recorder requires the `displayName` metadata property to handle the composition with labels.
> add displayname track metadata

- examples/react-client/fishjam-chat/src/App.tsx
- packages/react-client/src/hooks/useDevices.ts
I discussed the `useInitializeDevices` magic behavior with Tommy.
Alike Miron, Tommy also showed his fondness towards the simpler and less magical approach.
I decided to remove the props and keep the hook dead simple.
> Fce 464/simplify use initialize devices

- examples/react-client/fishjam-chat/src/App.tsx
- examples/react-client/fishjam-chat/src/components/DevicePicker.tsx
- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
- examples/react-client/fishjam-chat/src/components/VideoTracks.tsx
- packages/react-client/src/fishjamProvider.tsx
- packages/react-client/src/hooks/useFishjamClient.ts
- packages/react-client/src/hooks/useFishjamContext.ts
- packages/react-client/src/hooks/usePeerStatus.ts
- packages/react-client/src/hooks/useStatus.ts
- packages/react-client/src/hooks/useTrackManager.ts
- packages/react-client/src/types.ts
- packages/ts-client/src/FishjamClient.ts
The toggle function works in two modes: "soft" and "hard" (default). The user can invoke this function without any arguments. It starts (or resumes) the device and streams media if the user is connected. 
- Turns off the device
- Slower start
- Turns off the device LED
- Example usage: camera
- Only disables the device
- Faster start
- The device LED remains active
- Example usage: microphone
To unify the API with the Mobile SDK. It's important to implement this feature to avoid confusion:
https://linear.app/swmansion/issue/FCE-489/add-the-camera-and-mic-after-connecting-if-they-are-active-web
New feature (non-breaking change which adds functionality)
> FCE 410 Add toggle function

- packages/react-client/src/DeviceManager.ts
`start` function always updates the state
Start function didn't update internal state, so `MediaStream` was unreachable.
> FCE-542 DeviceManager start function updates the state

- packages/react-client/src/hooks/useScreenShare.ts
`stopStreaming()` on disconnect is only invoked if there is a screen share stream.
There is no need to issue a warning about screen sharing on every disconnect.
> FCE-543 Remove warn on every disconnect

- examples/react-client/fishjam-chat/src/App.tsx
- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
The FishjamChat now handles metadata correctly.
FishjamChat showed `trackId` instead of `displayName` on the video tile and didn't send the local participant's name in the metadata.
> FCE-548 Make videroom compatible with Fishjam Chat

- e2e-tests/react-client/scenarios/utils.ts
- examples/react-client/fishjam-chat/src/components/DevicePicker.tsx
- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
- examples/react-client/minimal-react/src/components/App.tsx
- examples/react-client/use-camera-and-microphone/src/Badge.tsx
- examples/react-client/use-camera-and-microphone/src/DeviceControls.tsx
- examples/react-client/use-camera-and-microphone/src/MainControls.tsx
- packages/react-client/src/fishjamProvider.tsx
- packages/react-client/src/hooks/useFishjamContext.ts
- packages/react-client/src/hooks/useParticipantStatus.ts
- packages/react-client/src/hooks/usePeerStatus.ts
- packages/react-client/src/hooks/useTrackManager.ts
- packages/react-client/src/index.ts
- packages/react-client/src/state.types.ts
List of peers statuses has been shortened to: `connecting`, `connected`, `error`, `idle`.
Removed: `connected`, `authenticated`, `closed`, `null`;
Renamed: `joined` -> `connected`
- The status `joined` was not descriptive.
- The user probably doesn't care about intermediate statuses (authenticated, web socket closed, web socket connected).
Breaking change (fix or feature that would cause existing functionality to not work as expected)
> FCE-458 Rename client statuses

- examples/react-client/fishjam-chat/src/App.tsx
- examples/react-client/fishjam-chat/src/components/Tile.tsx
Every tile on `fishjam-chat` displays:
- Audio waveform
- Muted indicator: 🔇 or 🔊
- Speaking indicator: 🗣 or 🤐
It is also possible to identify the audio origin (participant) and source (screen share vs. microphone).
To be able to visualise audio streams.
New feature (non-breaking change which adds functionality)
> FCE-550 Visualise audio props

- examples/ts-client/simple-app/src/main.ts
Local storage caused the same token to be set for all browser tabs. This resulted client B connecting, kicking out the peer A, then peer A tried to reconnect, and so on.
> Fix simple app example

- packages/ts-client/src/webrtc/CommandsQueue.ts
- packages/ts-client/src/webrtc/webRTCEndpoint.ts
The command handler waits for the `replaceTrack` promise to resolve.
If there were two `replaceTrack` calls in a row, the second one would not resolve until a new command entered the `commandsQueue`.
> FCE-650 Fix replace track promise

- packages/ts-client/src/webrtc/tracks/LocalTrack.ts
- packages/ts-client/src/webrtc/tracks/muteTrackUtils.ts
- packages/ts-client/src/webrtc/tracks/muteUnmuteTrackUtils.ts
Track in `trackContext` is assigned before emitting events. If `replaceTrack` fails, the opposite events will be emitted, and the state will be reverted.
To fix the bug
> FCE-652 Invalid state after mute/unmute track

- packages/react-client/src/fishjamProvider.tsx
- packages/react-client/src/hooks/useScreenShare.ts
The `stopStreaming` method checks if it is necessary to invoke `removeTrack`.
Screen sharing didn't end automatically after leaving the room.
> FCE-730 Disable screen share after leaving the room

- packages/ts-client/package.json
- yarn.lock
This PR updates dependencies for project.
- It looks like `react` and `ts-proto` are not required in project 🤔 
- we should use `@bufbuild/protobuf` as dependency
Let's have correct dependencies for project.
> [FCE-738] Add `@bufbuild/protobuf` to `ts-client` dependency

- examples/react-client/fishjam-chat/src/App.tsx
- examples/react-client/fishjam-chat/src/components/Tile.tsx
- examples/react-client/use-camera-and-microphone/src/DeviceControls.tsx
- packages/react-client/src/hooks/devices/useMicrophone.ts
- packages/react-client/src/hooks/public.ts
- packages/react-client/src/hooks/useFishjamClientState.ts
- packages/react-client/src/hooks/usePeers.ts
- packages/react-client/src/hooks/useVAD.ts
- packages/react-client/src/index.ts
- packages/react-client/src/types/public.ts
Implements `useVAD` hook allowing users to listen to VAD updates of selected peers.
Introduces changes to the way `fishjamClientState` stores peers data.
The `TrackContext` is kept as it is in the `FIshjamClient` to allow access to the track events.
Transformations of the peers now happens in the `usePeers` hook, just before exposing the data outside.
Users should have an opt-in way to listen to VAD updates.
> FCE-720 VAD hook

- examples/react-client/fishjam-chat/src/components/DevicePicker.tsx
- packages/react-client/src/hooks/devices/useCamera.ts
- packages/react-client/src/hooks/devices/useMicrophone.ts
`isStreaming` is set to false when the track is paused.
When the track was paused, `isStreaming` was false.
> FCE-658 `isStreaming` is false when track is paused

- packages/ts-client/src/FishjamClient.ts
- packages/ts-client/src/webrtc/CommandsQueue.ts
- packages/ts-client/src/webrtc/ConnectionManager.ts
- packages/ts-client/src/webrtc/tracks/Local.ts
- packages/ts-client/src/webrtc/tracks/LocalTrack.ts
- packages/ts-client/src/webrtc/webRTCEndpoint.ts
Introduce changes that support both old WebRTC endpoint and ElixirWebRTC Endpoint
> [FCE-731] Comply with ex_webrtc engine endpoint

- examples/react-client/fishjam-chat/src/components/CallToolbar.tsx
- examples/react-client/use-camera-and-microphone/src/ScreenShareControls.tsx
When the screen share window is closed, `NotAllowedError` is thrown. The `Share the screen` handler swallows this error.
When the user changes their mind during screen sharing and closes the browser window, an error appears in the console. This is a completely normal situation, so we should not log this error to the console.
> FCE-759 Hide the error if the user closes the screen share window

- examples/react-client/fishjam-chat/src/components/RoomView.tsx
- examples/react-client/minimal-react/src/components/App.tsx
- packages/react-client/src/hooks/usePeers.ts
- Deprecated `peers` in place of `remotePeers` in `usePeers` hook. 
- This change unifies hook API between mobile and web clients. 
> FCE-815: Rename `peers` to `remotePeers` in `usePeers`

- examples/react-client/fishjam-chat/src/components/RoomView.tsx
- examples/ts-client/minimal/src/main.ts
- examples/ts-client/simple-app/src/main.ts
- packages/react-client/src/fishjamProvider.tsx
- packages/react-client/src/hooks/useConnection.ts
- packages/react-client/src/hooks/useFishjamClientState.ts
- packages/react-client/src/hooks/useFishjamContext.ts
- packages/react-client/src/hooks/usePeerStatus.ts
- packages/react-client/src/hooks/usePeers.ts
- packages/react-client/src/hooks/useScreenShare.ts
- packages/react-client/src/hooks/useTrackManager.ts
- packages/react-client/src/types/internal.ts
- packages/react-client/src/types/public.ts
- packages/react-client/src/utils/track.ts
- packages/ts-client/src/FishjamClient.ts
- packages/ts-client/src/connectEventsHandler.ts
- packages/ts-client/src/index.ts
- packages/ts-client/src/reconnection.ts
- packages/ts-client/src/types.ts
Tidy up the metadata generic types.
Remove the `TrackMetadata` generic because we use a certain schema for track metadata.
Allow users to set metadata types using the `usePeers`  hook. 
When the metadata generics are not set, the type for both peer and server metadata is `Record<string, unknown>`.
> FCE-856/allow user to set metadata type on `usePeers`

- .github/workflows/fishjam-chat.yaml
Closes FCE-728
Decided to not use github pages as there are docs there. Deployment goes to https://chat.fishjam.io
> Add Fishjam Chat CD

- examples/react-client/fishjam-chat/src/components/RoomView.tsx
Removes playing local audio from fishjam chat.
> FCE-898 don't play local audio in fishjam chat

- packages/react-client/src/hooks/public.ts
- packages/react-client/src/hooks/useUpdatePeerMetadata.ts
- packages/react-client/src/index.ts
Add new `useUpdatePeerMetadata` hook, that would allow to update metadata after connection.
I've tested it with small code added in example app - it worked as expected.
Right now it is not possible to update metadata in web sdk.
> [FCE-930] Add useUpdatePeerMetadata hook

- .github/workflows/docs.yaml
- .github/workflows/fishjam-chat.yaml
- .github/workflows/node.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- package.json
- packages/protobufs/package.json
Protobufs should be generated on demand, not during the build step e.g. on CI.
Also resolves CI issues.
> Don't generate protobufs in build step

- README.md
- packages/react-client/LICENSE.txt
- packages/react-client/readme.md
- packages/ts-client/LICENSE.txt
- packages/ts-client/README.md
- packages/webrtc-client/LICENSE.txt
- packages/webrtc-client/README.md
This PR adds missing license files and fix img tag in readme files.
When generating documentation, I get errors that links are broken and HTML tag cannot be parsed
> [FCE-980] Fix links to licenses

- packages/react-client/src/hooks/devices/useInitializeDevices.ts
- Added params to initializeDevices function.
- Provide the ability for users to only ask for a single permission at a time. 
> FCE-457: Allow user to only initialise audio or video

- .github/workflows/node.yaml
- packages/protobufs/typedoc.json
- packages/react-client/src/FishjamProvider.tsx
- packages/react-client/src/devices/DeviceManager.ts
- packages/react-client/src/devices/mediaInitializer.ts
- packages/react-client/src/hooks/devices/useCamera.ts
- packages/react-client/src/hooks/devices/useMicrophone.ts
- packages/react-client/src/hooks/internal/useFishjamClientState.ts
- packages/react-client/src/hooks/useConnection.ts
- packages/react-client/src/hooks/usePeers.ts
- packages/react-client/src/hooks/useVAD.ts
- packages/react-client/src/index.ts
- packages/react-client/src/types/internal.ts
- packages/react-client/src/types/public.ts
- packages/react-client/src/utils/errors.ts
- packages/react-client/typedoc.json
- packages/ts-client/src/FishjamClient.ts
- packages/ts-client/src/index.ts
- packages/ts-client/src/types.ts
- packages/webrtc-client/src/webRTCEndpoint.ts
- typedoc.json
Export all types that are visible to end user, but were not yet exported
Fix typedoc syntax marked as incorrect
Update typedoc config to avoid part of validation for libraries that are not actively supported
I want to update our documentation, but as part of this process I want to remove warnings (and also add missing types into docs)
> [FCE-1038] Update types exports (and typedoc) to make `yarn docs` happy

- examples/react-client/fishjam-chat/src/components/RoomView.tsx
- examples/react-client/fishjam-chat/src/components/Tile.tsx
- packages/react-client/src/hooks/internal/useFishjamClientState.ts
- packages/react-client/src/hooks/usePeers.ts
- packages/react-client/src/index.ts
- packages/react-client/src/types/internal.ts
- packages/react-client/src/types/public.ts
- packages/react-client/src/utils/track.ts
Add branded types to most common IDs used in React Client. This way, these IDs can't be used as strings.
Make client code a little less buggy
> [FCE-1057] Add branded PeerId and TrackId

- packages/ts-client/src/reconnection.ts
Fixes low level peer metadata retrieval from RTC Endpoint.
The tsclient's `ReconnectionManager` was still unaware of the metadata being divided between peer and server.
The type of the metadata at the `LocalTrack` level is `unknown` and `ReconnectionManager` was wrongfully casting it as `PeerMetadata`.
This led to issues with providing correct metadata while reconnecting.
> FCE-1059/fix reconnection manager endpoint metadata retrieval

- packages/webrtc-client/src/internal.ts
- Refactored TrackContextImpl to avoid runtime errors caused by useDefineForClassFields.
Our tsconfig either enables `useDefineForClassFields` or sets `target: es2022` (enabling it by default). This can cause issues when subclassing, as this may be used before `super()` is called. More details [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier). 
This caused runtime errors with `WebRTCEndpoint`, especially in Playwright tests for `membrane-rtc-engine`.
We have two options:
1. Disable `useDefineForClassFields`, which is risky and could impact the codebase.
2. Refactor `TrackContextImpl` using declare to modify JS output and move initialization to the constructor.
I chose option 2 as it is …
> [FCE-1082] - Fix generated output of TrackContextImpl

- .github/workflows/docs.yaml
Update all actions related to publishing docs for this project
As of today, [actions/upload-artifact](https://github.com/actions/upload-artifact) is no longer available. So we have to update all actions that depend on it.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> [FCE-1126] Update publish docs action

- packages/react-client/src/index.ts
- packages/ts-client/src/FishjamClient.ts
- packages/ts-client/src/guards.ts
- packages/ts-client/src/index.ts
- packages/ts-client/src/reconnection.ts
- packages/ts-client/src/types.ts
- Always log a warning with the reason when the socket is closed
- Emit join error when a known error occurres.
- Socket errors were silently ignored and resulted in an unknown state. 
> [FCE-1112]: Better information on connected peer limit reached

- packages/react-client/src/hooks/devices/useMicrophone.ts
- packages/react-client/src/hooks/internal/useTrackManager.ts
- packages/react-client/src/types/internal.ts
Removes a stale closure from track manager and stop exposing `currentTrack` as it's not consumed anywhere.
Calling `toggleCamera` after leaving a room caused an exception, because the closure contained stale state which still had a `currentTrack`.
> FCE-1205/stale closure in track manager

- packages/react-client/src/hooks/internal/useScreenshareManager.ts
- packages/react-client/src/hooks/internal/useTrackManager.ts
- packages/react-client/src/types/internal.ts
- packages/ts-client/src/FishjamClient.ts
- packages/ts-client/src/errors.ts
- packages/ts-client/src/index.ts
- packages/ts-client/src/types.ts
`FishjamClient.addTrack` now checks if the track kind is allowed for the given room type and throws an error if it's not allowed.
`react-client` handles this error, i.e. the track is not added and a warning is logged to the console
This aims to give users better feedback when they attempt to add a video track to an audio-only room, as until now the behavior is that the peer joins the room and after a few seconds the entire `PeerConnection` crashes abruptly without any reasonable logs.
> Filter tracks based on room type

- .github/workflows/fishjam-chat.yaml
Stop deploying dependabot builds.
They don't have secrets access.
> Don't deploy fishjam chat as dependabotbot

- examples/react-client/fishjam-chat/src/components/DeviceSettings.tsx
- examples/react-client/fishjam-chat/src/components/ToggleButton.tsx
- packages/react-client/src/hooks/internal/devices/useDeviceManager.ts
- packages/react-client/src/hooks/internal/useTrackManager.ts
- packages/react-client/src/types/internal.ts
Preserves the initial state of device being turned/muted on/off after changing a device.
Current solution of the devices being always turned on during changing them is prone to user sending out data he possibly wouldn't like to.
> Keep the devices disabled/muted state after changing device.

- packages/react-client/src/utils/track.ts
Casts the Object.entries result back to a number.
The `maxBandwidth` object was broken due to it's keys being silently cast to string.
> Fix the `maxBandwidth` parameter 

- examples/react-client/fishjam-chat/src/components/DeviceSettings.tsx
- packages/react-client/src/hooks/devices/useCamera.ts
- packages/react-client/src/hooks/devices/useMicrophone.ts
- packages/react-client/src/hooks/internal/devices/useDeviceManager.ts
- packages/react-client/src/hooks/internal/devices/useMediaDevices.ts
Introduces `selectedCamera` and `selectedMicrophone` properties.
Deprecates `activeCamera` and `activeMicrophone` properties.
The "active device" property did not provide information about which device was selected when a device was off.
Right now, "selected device" shows the device that is being used or will be used after it is turned on. 
"Is device on" indicates if the device is turned on.
> FCE-1453 / Add current device property

- packages/webrtc-client/src/webRTCEndpoint.ts
Removes setting ongoing renegotiation flag after handling removed tracks.
There is no actual renegotiation in that case.
> FCE-1353 / fix endless renegotiation state

- examples/react-client/livestreaming/src/components/ConnectForm.tsx
- packages/ts-client/src/livestream.ts
Handles audio-only stream initialization. 
> Initialize stream when only audio is sent
