- examples/react-client/videoroom/.eslintrc.cjs
- examples/react-client/videoroom/.gitignore
- examples/react-client/videoroom/README.md
- examples/react-client/videoroom/index.html
- examples/react-client/videoroom/package.json
- examples/react-client/videoroom/postcss.config.cjs
- examples/react-client/videoroom/src/App.tsx
- examples/react-client/videoroom/src/AudioPlayer.tsx
- examples/react-client/videoroom/src/AudioVisualizer.tsx
- examples/react-client/videoroom/src/Button.tsx
- examples/react-client/videoroom/src/DevicePicker.tsx
- examples/react-client/videoroom/src/RoomConnector.tsx
- examples/react-client/videoroom/src/VideoPlayer.tsx
- examples/react-client/videoroom/src/client.ts
- examples/react-client/videoroom/src/index.css
- examples/react-client/videoroom/src/main.tsx
- examples/react-client/videoroom/src/vite-env.d.ts
- examples/react-client/videoroom/tailwind.config.cjs
- examples/react-client/videoroom/tsconfig.app.json
- examples/react-client/videoroom/tsconfig.json
- examples/react-client/videoroom/tsconfig.node.json
- examples/react-client/videoroom/vite.config.ts
- packages/react-client/src/DeviceManager.ts
- yarn.lock
Adds new code example that is a very simple version of videoroom.
> Fce 294/videoroomlike example

- packages/react-client/src/Client.ts
- packages/react-client/src/create.tsx
- packages/react-client/src/trackManager.ts
- packages/ts-client/src/FishjamClient.ts
- packages/ts-client/src/reconnection.ts
Describe your changes in detail.
> FCE-230 remove endpoint word from public api

- examples/react-client/videoroom/src/App.tsx
- examples/react-client/videoroom/src/client.ts
- packages/react-client/src/create.tsx
- packages/react-client/src/types.ts
Add use participants hook.
Simplify the api of displaying connected peers.
> Fce 307/use participants

- .github/workflows/docs.yaml
- README.md
- package.json
- packages/react-client/typedoc.json
- packages/ts-client/typedoc.json
- typedoc.json
- yarn.lock
Add basic documentation, available [here](https://fishjam-cloud.github.io/web-client-sdk/).
Docs will rebuild with each PR
Let's have some basic docs for project
> [FCE-352] Add typedoc

- packages/react-client/src/screenShareTrackManager.ts
Allowing user to describe constraints for screensharing.
> add constraints to screenshare interface

- examples/react-client/videoroom/src/RoomConnector.tsx
Small improvements for demo app:
- use latest RoomManager 
- store data user entered in previous session
- allow to copy values from Cloud UI
Let's make developers life easier
> [FCE-378] Use data from fixed room manager in Demo App

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
Prepare for releasing new version
> Bump 0.6.0

- packages/react-client/src/hooks/useTrackManager.ts
This PR fixes the issue described below.
As of now, changing the device during streaming resulted in black screen.
> fix changing devices

- examples/react-client/fishjam-chat/src/App.tsx
- examples/react-client/minimal-react/src/components/App.tsx
- examples/react-client/use-camera-and-microphone/src/MainControls.tsx
- packages/react-client/src/hooks/useParticipants.ts
- packages/react-client/src/index.ts
- packages/react-client/src/types.ts
Distinguish screenshare video/audio tracks from camera/microphone tracks.
> export distinguished screenshare tracks

- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
This change is the same as https://github.com/fishjam-cloud/mobile-client-sdk/pull/96
but for this repository's example
Above all we want to prevent accidental developer errors leading to frustration
> Accept Fishjam's path as Room Manager's

- examples/react-client/fishjam-chat/src/components/DevicePicker.tsx
- packages/react-client/src/hooks/useDevices.ts
`initializeDevices` is idempotent
Bugfix. `initializeDevices` doesn't work as expected
> FCE-484 initializeDevices starts two streams

- packages/react-client/src/hooks/useTrackManager.ts
`useTrackManager` adds a track when the participant joins the room
To unify API with mobile-sdk
New feature (non-breaking change which adds functionality)
> FCE-489 Add tracks on connect

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
> Relese 0.7.0

- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
- packages/ts-client/src/FishjamClient.ts
Describe your changes in detail.
> Fix stale types issue

- examples/react-client/fishjam-chat/src/App.tsx
- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
- examples/react-client/minimal-react/src/components/App.tsx
- examples/react-client/minimal-react/src/main.tsx
- examples/react-client/readme.md
- examples/react-client/use-camera-and-microphone/src/Badge.tsx
- examples/react-client/use-camera-and-microphone/src/DeviceControls.tsx
- examples/react-client/use-camera-and-microphone/src/MainControls.tsx
- packages/react-client/src/fishjamProvider.tsx
- packages/react-client/src/hooks/public.ts
- packages/react-client/src/hooks/useFishjamContext.ts
- packages/react-client/src/hooks/usePeerStatus.ts
- packages/react-client/src/hooks/usePeers.ts
- packages/react-client/src/hooks/useTrackManager.ts
- packages/react-client/src/index.ts
- packages/react-client/src/state.types.ts
- packages/react-client/src/types.ts
Bring back p word from another p word.
It has turned out to be a simpler approach.
> FCE-583 Back at it again with the `peer` word

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
> Release 0.7.1

- examples/react-client/fishjam-chat/src/components/DevicePicker.tsx
- packages/react-client/src/hooks/useTrackManager.ts
- packages/react-client/src/index.ts
- packages/react-client/src/types/internal.ts
- packages/react-client/src/types/public.ts
Describe your changes in detail.
> [FCE-609] Expose toggleMute and toggleDevice instead of toggle

- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
Make URL Parsing simpler
This change is simplifying URL parsing.
> Simplify parsing url

- examples/react-client/fishjam-chat/src/components/RoomConnector.tsx
Describe your changes in detail.
> Use session storage for peer name

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
> Release 0.7.2

- packages/react-client/src/hooks/useTrackManager.ts
Wraps methods in use callbacks. Simplify gathering metadata.
> Re-compute track manager methods only when required

- packages/react-client/src/hooks/useTrackManager.ts
Remove unnecessary `useMemo`
There was a bug.
> FCE-721 Fix toggle method

- examples/react-client/fishjam-chat/src/components/DevicePicker.tsx
- packages/react-client/src/DeviceManager.ts
- packages/react-client/src/hooks/devices/useCamera.ts
- packages/react-client/src/hooks/devices/useMicrophone.ts
- packages/react-client/src/types/public.ts
> Expose isMuted and device error

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
This is hotfix release to fix dependency issue (see #149 )
Bug that prevent from using latest release without some hacks on developer side
> Release 0.8.1

- packages/react-client/src/hooks/deviceManagers/useDeviceManager.ts
- packages/react-client/src/hooks/devices/useCamera.ts
- packages/react-client/src/hooks/devices/useDeviceApi.ts
- packages/react-client/src/hooks/devices/useMicrophone.ts
- packages/react-client/src/types/internal.ts
> Memoize device properties.

- .eslintrc.js
- examples/react-client/fishjam-chat/.eslintrc.cjs
- examples/react-client/fishjam-chat/src/components/AudioPlayer.tsx
- examples/react-client/fishjam-chat/src/components/AudioTracks.tsx
- examples/react-client/fishjam-chat/src/components/BlurToggle.tsx
- examples/react-client/fishjam-chat/src/components/DeviceSelect.tsx
- examples/react-client/fishjam-chat/src/components/JoinRoomCard.tsx
- examples/react-client/fishjam-chat/src/components/SettingsSheet.tsx
- examples/react-client/fishjam-chat/src/components/Tile.tsx
- examples/react-client/fishjam-chat/src/components/VideoPlayer.tsx
- examples/react-client/fishjam-chat/src/components/ui/badge.tsx
- examples/react-client/fishjam-chat/src/components/ui/button.tsx
- examples/react-client/fishjam-chat/src/hooks/useAutoConnect.ts
- examples/react-client/fishjam-chat/src/lib/utils.ts
- examples/react-client/fishjam-chat/src/utils/blur/BlurProcessor.tsx
Update lint config and fix new errors in example app.
Unify lint configuration in workspace
> [FCE-926] Fix lint config

- packages/react-client/src/FishjamProvider.tsx
- packages/react-client/src/fishjamProvider.tsx
- packages/react-client/src/hooks/useConnection.ts
- packages/react-client/src/hooks/usePeers.ts
- packages/react-client/src/hooks/useScreenShare.ts
- packages/react-client/src/hooks/useUpdatePeerMetadata.ts
- packages/react-client/src/hooks/useVAD.ts
- packages/react-client/src/index.ts
- packages/react-client/src/types/public.ts
- packages/react-client/typedoc.json
- yarn.lock
Small updates on typedoc comments, so it will look better on updated docusarus.
Better descriptions should be added once #212 is completed (with new hooks definitions)
Let's make documentation better.
> [FCE-992] Update typedoc comments

- packages/webrtc-client/src/tracks/Local.ts
Bring back sending simulcast related media events to Fishjam.
Fishjam supports media events messages again.
- [xl] Bug fix (non-breaking change which fixes an issue)
> FCE-990/uncomment simulcast media events

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
> Release 0.11.0

- .github/workflows/release.yaml
- Enable corepack for ts-client release workflow
- Release failed
> enable corepack for ts client

- packages/webrtc-client/src/tracks/Remote.ts
- Fixed a bug thanks to @roznawsk to use correct media event type.
- Wrong media event type was used when switching tracks.
> [FCE-1092]: Fix protobuf event for track encoding

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
> Release 0.13.0

- packages/react-client/src/hooks/devices/useInitializeDevices.ts
Add line that was lost in changes after CR.
> Add missing promise resolve.

- packages/react-client/src/FishjamProvider.tsx
- packages/react-client/src/contexts/fishjamState.ts
- packages/react-client/src/hooks/devices/useMicrophone.ts
- packages/react-client/src/hooks/internal/devices/useDeviceManager.ts
- packages/react-client/src/hooks/internal/useTrackManager.ts
- packages/react-client/src/hooks/usePeers.ts
- packages/react-client/src/hooks/useVAD.ts
- packages/react-client/src/types/internal.ts
- packages/react-client/src/utils/errors.ts
- packages/react-client/src/utils/track.ts
Removes unnecessary logic from track manager.
> FCE-1332 tidy up errors in track manager

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
- packages/webrtc-client/package.json
Bump versions
Part of release tram
> Release 0.16.0

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
- packages/webrtc-client/package.json
> release v0.16.1

- package.json
- packages/react-client/package.json
- packages/ts-client/package.json
- packages/webrtc-client/package.json
> Release 0.17.0

- packages/react-client/src/hooks/internal/devices/useDeviceManager.ts
- packages/react-client/src/hooks/internal/useScreenshareManager.ts
- packages/react-client/src/hooks/internal/useTrackManager.ts
- packages/react-client/src/hooks/internal/useTrackMiddleware.ts
- packages/react-client/src/index.ts
- packages/react-client/src/types/public.ts
Introduces async middlewares.
Smelter integration revealed that we are missing a case in which someone wants to create middleware with asynchronous dependencies.
> FCE-1544/async middlewares

- packages/react-client/src/FishjamProvider.tsx
- packages/react-client/src/devices/constraints.ts
I am still not sure about the desired state, maybe we should leave this on by default, but emphasise this in docs.
> FCE-1628 remove default echo cancellation and noise suppression

- .github/workflows/livestreaming-example.yaml
Deploys livestreaming example as a github page of this repository.
> Deploy livestreaming example

- examples/react-client/minimal-react/src/components/App.tsx
- examples/react-client/minimal-react/src/components/AudioPlayer.tsx
Every example for camera or mic uses the sandbox API. I needed to test a custom backend with them
> Add camera and mic to minimal react
